name: Test ci-core-dumper

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Crash Test ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Builder Info
        run: |
          which python
          python --version
      - uses: ./
        with:
          extra_gdb: "info auto-load"
      - name: Test
        run: |
          python build_crasher.py
          python -m ci_core_dumper exec python test_crasher.py
          ulimit -c unlimited
          python test_crasher.py

  docker:
    runs-on: ubuntu-latest
    name: Docker
    strategy:
      fail-fast: false
      matrix:
        include:
          - pyver: cp27-cp27m
            piparch: manylinux1_x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name: Docker
        run: |
          # can't use GHA native docker support since GHA magic binaries need .so absent from old manylinux images :(
          cat <<EOF > runit.sh
          #!/bin/sh
          set -e -x
          cd /io
          export PATH="/opt/python/${{ matrix.pyver }}/bin:\$PATH"
          which python

          python build_crasher.py
          python -m ci_core_dumper exec python test_crasher.py

          EOF
          cat runit.sh
          chmod +x runit.sh
          docker pull quay.io/pypa/${{ matrix.piparch }}
          docker run --privileged --rm -v `pwd`:/io quay.io/pypa/${{ matrix.piparch }} ${{ matrix.pre }} /io/runit.sh
